channels:
  - defaults
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - torch==1.6.0
  - pip:
    - git+https://github.com/morphomatics/morphomatics.git#egg=morphomatics
    - ipyvtklink
    - ipygany

